web/router.ex
defmodule Inventory.Router do
  use Inventory.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Inventory do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index

    resources "/buckets", BucketsController
    resources "/products", ProductsController
  end

  # Other scopes may use custom stacks.
  scope "/api", Inventory.Api, as: :api do
    pipe_through :api

    scope "/v1", V1, as: :v1 do
      resources "/buckets", BucketsController
      resources "/products", ProductsController
    end
  end
end

web/models/bucket.ex
defmodule Inventory.Bucket do
  use Inventory.Web, :model

  schema "buckets" do
    field :name, :string

    has_many :products_buckets, Inventory.ProductBucket
    has_many :products, through: [:products_buckets, :product]

    timestamps()
  end

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:name])
    |> validate_required([:name])
  end
end

web/controllers/api/v1/buckets_controller.ex
defmodule Inventory.Api.V1.BucketsController do
  use Inventory.Web, :controller

  alias Inventory.Bucket
  alias Inventory.ErrorHelpers

  def index(conn, _params) do
    render conn, "index.json", buckets: Repo.all(Bucket)
  end

  def show(conn, %{"id" => id}) do
    bucket = Repo.get!(Bucket, id) |> Repo.preload(:products)
    render conn, "bucket_with_products.json", bucket: bucket
  end

  def create(conn, %{"bucket" => bucket_params}) do
    changeset = Bucket.changeset(%Bucket{}, bucket_params)

    case Repo.insert(changeset) do
      {:ok, bucket} ->
        render conn, "show.json", bucket: bucket
      {:error, changeset} ->
        json(conn,  %{ errors: Ecto.Changeset.traverse_errors(changeset, &ErrorHelpers.translate_error/1) })
    end
  end

  def update(conn, %{"id" => id, "bucket" => bucket_params}) do
    bucket = Repo.get!(Bucket, id)
    changeset = Bucket.changeset(bucket, bucket_params)

    case Repo.update(changeset) do
      {:ok, bucket} ->
        render conn, "show.json", bucket: bucket
      {:error, changeset} ->
        json(conn,  %{ errors: Ecto.Changeset.traverse_errors(changeset, &ErrorHelpers.translate_error/1) })
    end
  end

  def delete(conn, %{"id" => id}) do
    bucket = Repo.get!(Bucket, id)
    Repo.delete!(bucket)
    json(conn, %{ deleted: true })
  end

end

web/views/buckets_view.ex
defmodule Inventory.BucketsView do
  use Inventory.Web, :view

  def handler_info(conn) do
    "Request Handled By: #{controller_module conn}.#{action_name conn}"
  end

  def connection_keys(conn) do
    conn
    |> Map.from_struct()
    |> Map.keys()
  end

end

web/templates/buckets/edit.html.eex
<%= form_for @changeset, buckets_path(@conn, :update, @changeset.data.id), fn f -> %>
  <%= render Inventory.BucketsView, "form.html", f: f %>
<% end %>

web/templates/buckets/form.html.eex
<label>
  Name: <%= text_input @f, :name %>
</label>

<%= submit "Submit" %>

web/templates/buckets/index.html.eex
<h1>Buckets</h1>

<ul>
  <%= for bucket <- @buckets do %>
    <li>
      <strong><%= bucket.name %></strong>
      <%= link "Edit", to: buckets_path(Inventory.Endpoint, :edit, bucket.id) %>
      <%= link "Delete", to: buckets_path(Inventory.Endpoint, :delete, bucket.id), method: :delete, data: [confirm: "Delete Bucket?"] %>
    </li>
  <% end %>
</ul>

<%= link "New Bucket", to: buckets_path(Inventory.Endpoint, :new) %>

web/templates/buckets/new.html.eex
<%= form_for @changeset, buckets_path(@conn, :create), fn f -> %>
  <%= render Inventory.BucketsView, "form.html", f: f %>
<% end %>

web/templates/buckets/show.html.eex
<h1><%= @bucket.name %></h1>

<%= if @bucket.products do %>
  <h2>Products</h2>

  <ul>
    <%= for product <- @bucket.products do %>
      <li>
        <strong><%= product.title %></strong>
        <%= link "Edit", to: products_path(Inventory.Endpoint, :edit, product.id) %>
        <%= link "Delete", to: products_path(Inventory.Endpoint, :delete, product.id), method: :delete, data: [confirm: "Delete product?"] %>
      </li>
    <% end %>
  </ul>
<% end %>